version: '3.3'
services:

    main:
      container_name: main
      build :
        context: .
        dockerfile: ./main/DockerFile
      volumes:
        - ./main:/app
      ports:
        - "3000:3000"
      environment:
        - MONGO_URL=mongodb://userdb:27017/demo
      depends_on:
        - userdb

    
    userdb:
      image: mongo:latest
      container_name: userdb
      ports:
        - "27017:27017"
      restart: always
      environment:
        MONGO_INITDB_DATABASE: demo
      volumes:
        - ./init-users.js:/docker-entrypoint-initdb.d/init-users.js:ro
        - /data/db