version: '3.3'
services:

    main:
      container_name: main
      build :
        context: .
        dockerfile: ./main/DockerFile
      volumes:
        - ./main:/app
      ports:
        - "3000:3000"
      environment:
        - AUTHENTICATION_SERVICE_URL=http://authentication-service:3001
        - MONGO_URL=mongodb://messengerbdd:27017/demo
      depends_on:
        - messengerbdd

    
    messengerbdd:
      image: mongo:latest
      container_name: messengerbdd
      ports:
        - "27017:27017"
      restart: always
      environment:
        MONGO_INITDB_DATABASE: demo
      volumes:
        - ./init-users.js:/docker-entrypoint-initdb.d/init-users.js:ro
        - /data/db

    authentication-service:
      container_name: authentication-service
      build:
        context: .
        dockerfile: ./authentication-service/DockerFile
      volumes:
        - ./authentication-service:/app
      ports:
        - "3001:3000"
      environment:
        - MONGO_URL=mongodb://messengerbdd:27017/demo
        - JWT_SECRET=${JWT_SECRET}
      depends_on:
        - messengerbdd